<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GRBOGON" failures="1" tests="3" name="Test" time="0.106" errors="0" timestamp="2021-07-15T13:19:07 IST">
  <testcase classname="testng_practice.testngreport" name="skipTest" time="0.012">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase classname="testng_practice.testngreport" name="passTest" time="0.015"/>
  <testcase classname="testng_practice.testngreport" name="failTest" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng_practice.testngreport.failTest(testngreport.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
</testsuite> <!-- Test -->
